[project]
name = "projet-5-ml-deploiement"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "thibaultdautheville@outlook.fr", email = "thibaultdautheville@outlook.fr" }
]
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.128.8",
    "pandas>=2.3.3",
    "psycopg[binary]>=3.2.13",
    "scikit-learn>=1.6.1",
    "sqlalchemy>=2.0.54",
    "uvicorn>=0.39.0",
    "xgboost>=2.1.4",
]




[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=8.4.2",
    "pytest-cov>=7.1.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
markers = [
    "integration: tests nécessitant une vraie instance PostgreSQL",
]